### ISSUE TITLE
Fix NerscAllocationInfo source so it doesn't go OFFLINE after one failure

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#110]
The NerscAllocationInfo.py (decisionengine_modules/NERSC/sources directory) errors out currently if it ever
 fails to contact the NERSC NEWT API web site.  This is not a good thing since that web site is not very reliable 
and can easily time out and also is not available during NERSC scheduled downtimes.

Please do something to catch the exception when this happens.  Really this source needs to run only once a day because the numbers are only updated once per day.  We can just use the previous datablock until such time as the data is available again.

The query in question is at line 40 of the existing code.

**Comment by DmitryLitvintsev** [comment]
Steve,
do you have an example of associated stack trace bu chance?

**Comment by DmitryLitvintsev** [comment]
2019-12-01 05:07:02,224 - root - TaskManager - 224399 - NerscAllocationInfo - ER
ROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 279, in run_source
data = src.worker.acquire()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 72, in acquire
self.send_query()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 40, in send_query
values = self.newt.get_usage(username)
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 62, in get_usage
r = self.session.get(user_url)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 489, in get
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 477, in req
uest
prep.url, proxies, stream, verify, cert
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 589, in sen
d
hooks = request.hooks
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in sen
d
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Also
2019-09-10 10:57:26,124 - root - TaskManager - 361715 - NerscAllocationInfo - ER
ROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 279, in run_source
data = src.worker.acquire()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 72, in acquire
self.send_query()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 40, in send_query
values = self.newt.get_usage(username)
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 63, in get_usage
r.raise_for_status()
File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise
_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

Also
2019-09-16 15:06:00,863 - root - TaskManager - 428932 - NerscAllocationInfo - ER
ROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 279, in run_source
data = src.worker.acquire()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 72, in acquire
self.send_query()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 40, in send_query
values = self.newt.get_usage(username)
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 63, in get_usage
r.raise_for_status()
File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise
_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR

Also2019-10-24 10:55:04,465 - root - TaskManager - 188538 - NerscAllocationInfo - ER
ROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 279, in run_source
data = src.worker.acquire()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 72, in acquire
self.send_query()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 40, in send_query
values = self.newt.get_usage(username)
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 60, in get_usage
self._login()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 47, in _login
r = self.session.post(login_url, data=postfields)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 520, in pos
t
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 477, in req
uest
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 589, in sen
d2019-10-24 10:55:04,465 - root - TaskManager - 188538 - NerscAllocationInfo - ER
ROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 279, in run_source
data = src.worker.acquire()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 72, in acquire
self.send_query()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/Ne
rscAllocationInfo.py", line 40, in send_query
values = self.newt.get_usage(username)
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 60, in get_usage
self._login()
File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.
py", line 47, in _login
r = self.session.post(login_url, data=postfields)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 520, in pos
t
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 477, in req
uest
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 589, in sen
d
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in sen
d
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in sen
d
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

I am not quite sure the mechanics of how to handle an error like this inside a source
but logically you should catch the exception, print a warning and continue.. if there is
an older data block available in the channel then that should continue to be used and pushed forward
to the transforms.

**Comment by DmitryLitvintsev** [comment]
The point is - acquire will return what in this case. An empty frame?

**Comment by DmitryLitvintsev** [comment]
I understand what you are asking.  There are only limited things the source can do on its own with nodata --namely raise an exception or return an empty frame.
Returning an empty frame is not ideal because there are various parts of the logic engine (in the decision engine channel)  that attempt to pull specific values out of the frame, and if that frame is an empty frame, those will have an error.
This is pointing to something which in the long term should be addressed in the framework.
What happens now the way the code works is that the Nersc channel immediately goes offline
but the resource_request channel still has access to the previous data block that was good that it
retrieves via source proxy.  in that state the DE stays up until such time as you have to restart it, and if it tries to restart while NERSC is still down, you can't do it.

**Comment by DmitryLitvintsev** [comment]
This issue is now moot because NERSC has changed the whole structure of this API as described in issue #62.  So now the existing routine is still running but fetching the values as they were frozen at the end of the 2019 allocation year, on January 14, 2020.

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/184

**Comment by StevenCTimm** [comment]
The fix for issue #231 also fixed this issue.  This issue can be closed.
