### ISSUE TITLE
AWS FigureOfMerit unit test fails

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#201]
One of the AWS unit tests fails like so:

```
decisionengine_modules/AWS/tests/test_FigureOfMerit.py::TestFigureOfMerit::test_transform FAILED [ 17%]
=================================== FAILURES ===================================
_______________________ TestFigureOfMerit.test_transform _______________________
Traceback (most recent call last):
  File "/github/workspace/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EntryName'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/github/workspace/decisionengine_modules/AWS/tests/test_FigureOfMerit.py", line 53, in test_transform
    res = fom.transform(data_block)
  File "/github/workspace/decisionengine_modules/AWS/transforms/FigureOfMerit.py", line 91, in transform
    price_perf_row['EntryName'] = r1['EntryName'].values[0]
  File "/github/workspace/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/github/workspace/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EntryName'
=============================== warnings summary ===============================
venv/lib64/python3.6/distutils/__init__.py:4
  /github/workspace/venv/lib64/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED decisionengine_modules/AWS/tests/test_FigureOfMerit.py::TestFigureOfMerit::test_transform
============== 1 failed, 84 passed, 1 warning in 66.45s (0:01:06) ==============
```

This is due to fixture no longer reflecting what code produce (lack of column "EntryName" in the fixture) .

**Comment by hyunwoo18** [comment]
I finished this issue but I can not find a way to close on this page..

**Comment by DmitryLitvintsev** [comment]
https://github.com/HEPCloud/decisionengine_modules/pull/204
