### ISSUE TITLE
GceBillingInfo.py dies with exception in 1.2 branch python36

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#223]
In a failure mode very similar to what we saw in the python 2.7 1.1 series, we see the following:

 for all tasks to run
2020-05-13 16:22:23,991 - oauth2client.client - client - 16933 - GCEBillingInfo 
- INFO - Refreshing access_token
2020-05-13 16:22:24,283 - root - GCEBillingInfo - 16933 - GCEBillingInfo - ERROR
 - not all arguments converted during string formatting
2020-05-13 16:22:24,283 - root - TaskManager - 16933 - GCEBillingInfo - ERROR - 
Exception running source GCEBillingInfo : local variable 'CorrectedBillSummaryDi
ct' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/Ta
skManager.py", line 287, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/GCE/sources/GCEB
illingInfo.py", line 459, in acquire
    return {PRODUCES[0]: pd.DataFrame([CorrectedBillSummaryDict])}
UnboundLocalError: local variable 'CorrectedBillSummaryDict' referenced before a
ssignment

---

Most likely the error is some kind of authentication error (which is caught, but then leaves a blank field which gives the exception) , but standalone run as a test the source works and the credential is good.

**Comment by DmitryLitvintsev** [comment]
This seems to be the same as 

https://github.com/HEPCloud/decisionengine_modules/issues/209

so runs on python2 fails in python3

**Comment by StevenCTimm** [comment]
The test programs written for #209 work in python 2 or 3, but the code as delivered in 3 doesn't;

**Comment by DmitryLitvintsev** [comment]
this is test program
```
Last login: Wed May 13 22:12:28 on ttys097
mac-131313:~ dmitrylitvintsev$ ssh root@fermicloud371
ssh: Could not resolve hostname fermicloud371: nodename nor servname provided, or not known
mac-131313:~ dmitrylitvintsev$ ssh root@fermicloud371.fnal.gob
ssh: Could not resolve hostname fermicloud371.fnal.gob: nodename nor servname provided, or not known
mac-131313:~ dmitrylitvintsev$ ssh root@fermicloud371.fnal.gob
ssh: Could not resolve hostname fermicloud371.fnal.gob: nodename nor servname provided, or not known
mac-131313:~ dmitrylitvintsev$ ssh root@fermicloud371.fnal.gov
Warning: No xauth data; using fake authentication data for X11 forwarding.
Last login: Wed May 13 22:09:25 2020 from 131.225.80.67
                              NOTICE TO USERS

       This  is a Federal computer (and/or it is directly connected to a
       Fermilab local network system) that is the property of the United
       States Government.  It is for authorized use only.  Users (autho-
       rized or unauthorized) have no explicit or  implicit  expectation
       of privacy.

       Any  or  all uses of this system and all files on this system may
       be intercepted, monitored, recorded,  copied, audited, inspected,
       and  disclosed  to authorized site, Department of Energy  and law
       enforcement personnel, as  well as authorized officials of  other
       agencies,  both  domestic and foreign.  By using this system, the
       user consents to such interception, monitoring, recording,  copy-
       ing,  auditing,  inspection,  and disclosure at the discretion of
       authorized site or Department of Energy personnel.

       Unauthorized or improper use of this system may result in  admin-
       istrative  disciplinary  action and civil and criminal penalties.
       By continuing to use this system you indicate your  awareness  of
       and  consent to these terms and conditions of use.  LOG OFF IMME-
       DIATELY if you do not agree to  the  conditions  stated  in  this
       warning.

       Fermilab  policy  and  rules for computing, including appropriate
       use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
[root@fermicloud371 ~]# ls /home/decisionengine/.boto
ls: cannot access /home/decisionengine/.boto: No such file or directory
[root@fermicloud371 ~]# exit
logout
^[[AConnection to fermicloud371.fnal.gov closed.
mac-131313:~ dmitrylitvintsev$ ssh root@hepcsvc03.fnal.gov
Warning: No xauth data; using fake authentication data for X11 forwarding.
Last login: Wed May 13 22:09:59 2020 from 131.225.80.67
                              NOTICE TO USERS

       This  is a Federal computer (and/or it is directly connected to a
       Fermilab local network system) that is the property of the United
       States Government.  It is for authorized use only.  Users (autho-
       rized or unauthorized) have no explicit or  implicit  expectation
       of privacy.

       Any  or  all uses of this system and all files on this system may
       be intercepted, monitored, recorded,  copied, audited, inspected,
       and  disclosed  to authorized site, Department of Energy  and law
       enforcement personnel, as  well as authorized officials of  other
       agencies,  both  domestic and foreign.  By using this system, the
       user consents to such interception, monitoring, recording,  copy-
       ing,  auditing,  inspection,  and disclosure at the discretion of
       authorized site or Department of Energy personnel.

       Unauthorized or improper use of this system may result in  admin-
       istrative  disciplinary  action and civil and criminal penalties.
       By continuing to use this system you indicate your  awareness  of
       and  consent to these terms and conditions of use.  LOG OFF IMME-
       DIATELY if you do not agree to  the  conditions  stated  in  this
       warning.

       Fermilab  policy  and  rules for computing, including appropriate
       use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
emacs -------------------------------------------------------------------------------
                     ..::Powered by ECF-SSI::..                      

   Hostname: hepcsvc03.fnal.gov                                                
 OS Release: SLF 7.7 (Nitrogen)         Puppet Zone: gco                       
         IP: 131.225.240.95             Puppet Role: decisionengine/de_itb     
     Subnet: 255.255.255.0               Puppet Env: gco_timm_decision_testing

    Support: 8x5                           Downtime: 3rdThuGCO                 
   Warranty: 2015-10-16 - 2020-10-16 (WARRANTY ON SITE 8 HR RESPONSE)

     Kernel: 3.10.0-1062.12.1                  Arch: x86_64                    
        RAM: 62.65 GiB                         Swap: 4.00 GiB                  
      Cores: 16                             Virtual: physical                  
 Make/Model: KOI COMPUTERS / KOI-FY15: CONFIG#4                                

     Uptime: 61 days                       Load Avg: 0.14 0.08 0.08            
 SSH Logins: 3 (3 root)                    Location: fcc-2-1437                

    Contact: Farrukh Khan <fkhan@fnal.gov> [8859]                              
    Contact: Steven Timm <timm@fnal.gov> [8525]                                

     Puppet: ran within 8 hours and is not failing                 
   check_mk: no problems (https://ssinagios.fnal.gov/)             
------------------------------------------------------------------------------
[root@hepcsvc03 ~]# emacs -nw GCEBillingInfo.py
[root@hepcsvc03 ~]# python GCEBillingInfo.py
No handlers could be found for logger "root"
[root@hepcsvc03 ~]# !em
emacs -nw GCEBillingInfo.py
[root@hepcsvc03 ~]# grep 'basiCo' *py 
[root@hepcsvc03 ~]# emacs -nw GCEBillingInfo.py
[root@hepcsvc03 ~]# python GCEBillingInfo.py
ERROR:root:Unable to download GCE billing file names because auth is not set up
INFO:root:Calculated corrected bill summary for google
INFO:root:{}
[root@hepcsvc03 ~]# ssh root@fermicloud155
Last login: Wed May 13 16:25:47 2020 from 131.225.78.3
                              NOTICE TO USERS

       This  is a Federal computer (and/or it is directly connected to a
       Fermilab local network system) that is the property of the United
       States Government.  It is for authorized use only.  Users (autho-
       rized or unauthorized) have no explicit or  implicit  expectation
       of privacy.

       Any  or  all uses of this system and all files on this system may
       be intercepted, monitored, recorded,  copied, audited, inspected,
       and  disclosed  to authorized site, Department of Energy  and law
       enforcement personnel, as  well as authorized officials of  other
       agencies,  both  domestic and foreign.  By using this system, the
       user consents to such interception, monitoring, recording,  copy-
       ing,  auditing,  inspection,  and disclosure at the discretion of
       authorized site or Department of Energy personnel.

       Unauthorized or improper use of this system may result in  admin-
       istrative  disciplinary  action and civil and criminal penalties.
       By continuing to use this system you indicate your  awareness  of
       and  consent to these terms and conditions of use.  LOG OFF IMME-
       DIATELY if you do not agree to  the  conditions  stated  in  this
       warning.

       Fermilab  policy  and  rules for computing, including appropriate
       use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
cd
ls -altr
[root@fermicloud155 ~]# cd
[root@fermicloud155 ~]# ls -altr
total 996
-rwxr-xr-x.  1 root           root        176 Jan 24  2019 .bash_profile
drwx------.  3 root           root       4096 Jan 24  2019 .dbus
drwxr-xr-x.  4 root           root       4096 Jan 24  2019 .cache
drwx------.  4 root           root       4096 Jan 24  2019 .config
drwx------.  2 root           root       4096 Jan 24  2019 .gnupg
drwxr-xr-x.  2 root           root       4096 Jan 24  2019 bin
drwxr-xr-x.  2 root           root       4096 Jan 24  2019 tmp
-rw-r-----.  1 root           root         20 Jan 24  2019 .forward
-rwxr-xr-x.  1 root           root        913 Jan 24  2019 .bashrc
-rw-r--r--.  1 root           root        778 Jan 24  2019 .zshrc
drwxr-----.  3 root           root       4096 Jan 24  2019 .pki
drwx------.  2 root           root       4096 Jan 24  2019 .ssh
-rw-r--r--.  1 root           root        658 Jan 24  2019 testpandas.py
-rw-r--r--.  1 root           root      36558 Feb 19  2019 .zcompdump
-rw-------.  1 root           root        122 Feb 19  2019 .zhistory
-rw-r--r--   1 root           root        680 Apr 17  2019 update.sh
-rwxr-xr-x   1 root           root        309 Jun 14  2019 checkkernel.sh
drwxr-xr-x.  3 root           root       4096 Nov 26 14:50 .bash
drwxr-xr-x.  4 root           root       4096 Feb  4 14:50 .zsh
-rwxr-xr-x   1 root           root       1731 Feb 17 15:34 update6.sh
-rw-r--r--.  1 root           root        334 Mar 25 09:57 k5login_global
-rw-------   1 root           root         40 Apr 22 10:50 .psql_history
-rw-------   1 root           root         87 Apr 22 11:14 .sqlite_history
-rw-r--r--   1 decisionengine hepcloud 177600 Apr 22 15:50 sample_gcebilling.log.debug
drwx------   3 root           root       4096 Apr 22 16:08 .emacs.d
-rw-r--r--   1 root           root      22397 Apr 22 16:29 hepcloud-fnal-2018-07-17.csv
drwxr-xr-x   3 root           root       4096 Apr 22 16:29 .gsutil
-rwxr-xr-x   1 root           root     378880 Apr 22 21:24 modules-rpmbuild-2.7.tar
drwxr-xr-x   3 root           root       4096 Apr 22 21:24 var
drwxr-xr-x   2 root           root       4096 Apr 23 14:18 glideinwms-3.4.2
-rw-r--r--   1 root           root        658 Apr 23 15:58 testpandas2.py
drwxr-xr-x   2 root           root       4096 Apr 23 16:23 glideinwms-3.6.2
drwxr-xr-x.  2 root           root       4096 Apr 23 16:54 .aws
-rw-------   1 root           root       1909 Apr 23 17:05 .viminfo
-rw-r--r--   1 root           root          0 Apr 24 18:51 foo.log
-rwxr-xr-x   1 root           root      23815 Apr 24 18:53 GCEBillingInfo.py~
-rwxr-xr-x   1 root           root      24738 Apr 24 19:01 GCEBillingInfo_new.py~
-rwxr-xr-x   1 root           root      24740 Apr 24 19:04 GCEBillingInfo_new.py
-rwxr-xr-x   1 root           root      23752 Apr 24 19:21 GCEBillingInfo_old.py
-rwxr-xr-x   1 root           root      23764 Apr 24 19:35 GCEBillingInfo.py3
-rw-------.  1 root           root        160 Apr 24 19:42 .lesshst
-rwxr-xr-x   1 root           root      24705 Apr 24 20:09 GCEBillingInfo.py
-rw-r--r--   1 root           root        370 Apr 24 20:17 gce_test.py~
-rw-r--r--   1 root           root        370 Apr 24 20:21 gce_test.py
-rwxr-xr-x   1 root           root       1160 May  4 16:33 update78.sh
-rw-------   1 root           root        423 May  6 09:16 k5login.old
-rw-r--r--.  1 root           root         80 May  6 09:50 hktemp.log
dr-xr-xr-x. 19 root           root       4096 May  6 09:51 ..
-rw-------   1 root           root        423 May  6 09:53 .k5login
drwxr-xr-x.  2 root           root       4096 May 13 13:59 .matplotlib
-rw-------   1 root           root        340 May 13 16:25 .Xauthority
drwxr-x---. 19 root           root       4096 May 13 16:25 .
-rw-------.  1 root           root      55635 May 13 18:34 .bash_history
[root@fermicloud155 ~]# less gce_test.py
[root@fermicloud155 ~]# python gce_test.py
Traceback (most recent call last):
  File "gce_test.py", line 14, in <module>
    file_obj = uri.get_bucket()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 181, in get_bucket
    conn = self.connect()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 140, in connect
    **connection_args)
  File "/usr/lib/python2.7/site-packages/boto/gs/connection.py", line 47, in __init__
    suppress_consec_slashes=suppress_consec_slashes)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 3 handlers were checked. ['OAuth2Auth', 'OAuth2ServiceAccountAuth', 'HmacAuthV1Handler'] Check your credentials
[root@fermicloud155 ~]# less gce_test.py
[root@fermicloud155 ~]# ls root@fermicloud155
ls: cannot access root@fermicloud155: No such file or directory
[root@fermicloud155 ~]# cat gce_test.py
import boto
import pandas as pd
from boto.exception import NoAuthHandlerFound
import os 
import gcs_oauth2_boto_plugin

GOOGLE_STORAGE = 'gs'
LOCAL_FILE = 'file'

#os.environ['BOTO_CONFIG']  = "/home/decisionengine/.boto"

# Access list of files from Goggle storage bucket
uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
file_obj = uri.get_bucket()
    
[root@fermicloud155 ~]# ls /home/decisionengine/.boto
/home/decisionengine/.boto
[root@fermicloud155 ~]# scp gce_test.py root@hepcsvc03:~/
gce_test.py                                                                                                                             100%  370   397.4KB/s   00:00    
[root@fermicloud155 ~]# exit
logout
Connection to fermicloud155 closed.
[root@hepcsvc03 ~]# ssh root@hepcsvc03
Last login: Wed May 13 22:14:12 2020 from 131.225.77.248
                              NOTICE TO USERS

       This  is a Federal computer (and/or it is directly connected to a
       Fermilab local network system) that is the property of the United
       States Government.  It is for authorized use only.  Users (autho-
       rized or unauthorized) have no explicit or  implicit  expectation
       of privacy.

       Any  or  all uses of this system and all files on this system may
       be intercepted, monitored, recorded,  copied, audited, inspected,
       and  disclosed  to authorized site, Department of Energy  and law
       enforcement personnel, as  well as authorized officials of  other
       agencies,  both  domestic and foreign.  By using this system, the
       user consents to such interception, monitoring, recording,  copy-
       ing,  auditing,  inspection,  and disclosure at the discretion of
       authorized site or Department of Energy personnel.

       Unauthorized or improper use of this system may result in  admin-
       istrative  disciplinary  action and civil and criminal penalties.
       By continuing to use this system you indicate your  awareness  of
       and  consent to these terms and conditions of use.  LOG OFF IMME-
       DIATELY if you do not agree to  the  conditions  stated  in  this
       warning.

       Fermilab  policy  and  rules for computing, including appropriate
       use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
cd
pyth------------------------------------------------------------------------------
                     ..::Powered by ECF-SSI::..                      

   Hostname: hepcsvc03.fnal.gov                                                
 OS Release: SLF 7.7 (Nitrogen)         Puppet Zone: gco                       
         IP: 131.225.240.95             Puppet Role: decisionengine/de_itb     
     Subnet: 255.255.255.0               Puppet Env: gco_timm_decision_testing

    Support: 8x5                           Downtime: 3rdThuGCO                 
   Warranty: 2015-10-16 - 2020-10-16 (WARRANTY ON SITE 8 HR RESPONSE)

     Kernel: 3.10.0-1062.12.1                  Arch: x86_64                    
        RAM: 62.65 GiB                         Swap: 4.00 GiB                  
      Cores: 16                             Virtual: physical                  
 Make/Model: KOI COMPUTERS / KOI-FY15: CONFIG#4                                

     Uptime: 61 days                       Load Avg: 0.02 0.04 0.05            
 SSH Logins: 3 (3 root)                    Location: fcc-2-1437                

    Contact: Farrukh Khan <fkhan@fnal.gov> [8859]                              
    Contact: Steven Timm <timm@fnal.gov> [8525]                                

     Puppet: ran within 8 hours and is not failing                 
   check_mk: no problems (https://ssinagios.fnal.gov/)             
------------------------------------------------------------------------------
[root@hepcsvc03 ~]# cd
[root@hepcsvc03 ~]# python gce_test.py
Traceback (most recent call last):
  File "gce_test.py", line 14, in <module>
    file_obj = uri.get_bucket()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 181, in get_bucket
    conn = self.connect()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 140, in connect
    **connection_args)
  File "/usr/lib/python2.7/site-packages/boto/gs/connection.py", line 47, in __init__
    suppress_consec_slashes=suppress_consec_slashes)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 3 handlers were checked. ['OAuth2Auth', 'OAuth2ServiceAccountAuth', 'HmacAuthV1Handler'] Check your credentials
[root@hepcsvc03 ~]# less gce_test.py
[root@hepcsvc03 ~]# cat gce_test.py
import boto
import pandas as pd
from boto.exception import NoAuthHandlerFound
import os 
import gcs_oauth2_boto_plugin

GOOGLE_STORAGE = 'gs'
LOCAL_FILE = 'file'

#os.environ['BOTO_CONFIG']  = "/home/decisionengine/.boto"

# Access list of files from Goggle storage bucket
uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
file_obj = uri.get_bucket()
    
[root@hepcsvc03 ~]# python
Python 2.7.5 (default, Aug  6 2019, 16:39:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> import gcs_oauth2_boto_plugin
>>> 
>>> GOOGLE_STORAGE = 'gs'
>>> uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
>>> file_obj = uri.get_bucket()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 181, in get_bucket
    conn = self.connect()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 140, in connect
    **connection_args)
  File "/usr/lib/python2.7/site-packages/boto/gs/connection.py", line 47, in __init__
    suppress_consec_slashes=suppress_consec_slashes)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 3 handlers were checked. ['OAuth2Auth', 'OAuth2ServiceAccountAuth', 'HmacAuthV1Handler'] Check your credentials
>>> 
[root@hepcsvc03 ~]# exit
logout
Connection to hepcsvc03 closed.
[root@hepcsvc03 ~]# ssh root@fermicloud155
Last login: Wed May 13 22:24:17 2020 from 131.225.240.95
                              NOTICE TO USERS

       This  is a Federal computer (and/or it is directly connected to a
       Fermilab local network system) that is the property of the United
       States Government.  It is for authorized use only.  Users (autho-
       rized or unauthorized) have no explicit or  implicit  expectation
       of privacy.

       Any  or  all uses of this system and all files on this system may
       be intercepted, monitored, recorded,  copied, audited, inspected,
       and  disclosed  to authorized site, Department of Energy  and law
       enforcement personnel, as  well as authorized officials of  other
       agencies,  both  domestic and foreign.  By using this system, the
       user consents to such interception, monitoring, recording,  copy-
       ing,  auditing,  inspection,  and disclosure at the discretion of
       authorized site or Department of Energy personnel.

       Unauthorized or improper use of this system may result in  admin-
       istrative  disciplinary  action and civil and criminal penalties.
       By continuing to use this system you indicate your  awareness  of
       and  consent to these terms and conditions of use.  LOG OFF IMME-
       DIATELY if you do not agree to  the  conditions  stated  in  this
       warning.

       Fermilab  policy  and  rules for computing, including appropriate
       use, may be found at http://www.fnal.gov/cd/main/cpolicy.html
[root@fermicloud155 ~]# python GCEBillingInfo_new.py
ERROR:logger:Unable to download GCE billing file names because auth is not set up
Empty DataFrame
Columns: []
Index: [0]
[root@fermicloud155 ~]# python GCEBillingInfo.py
[root@fermicloud155 ~]# less GCEBillingInfo.py
[root@fermicloud155 ~]# less GCEBillingInfo_new.py
[root@fermicloud155 ~]# less GCEBillingInfo_new.py
[root@fermicloud155 ~]# less gce_test.py

import boto
import pandas as pd
from boto.exception import NoAuthHandlerFound
import os 
import gcs_oauth2_boto_plugin

GOOGLE_STORAGE = 'gs'
LOCAL_FILE = 'file'

#os.environ['BOTO_CONFIG']  = "/home/decisionengine/.boto"

# Access list of files from Goggle storage bucket
uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
file_obj = uri.get_bucket()
```

**Comment by StevenCTimm** [comment]
First of all I should have said that the python 3.6 installation in question is on fermicloud117 
to which I have now added litvinse@FNAL.GOV to the /root/.k5login

And the program should be run as user "decisionengine" to see the right credentials.

Under those conditions the test program does work.

[root@fermicloud117 ~]# su - decisionengine
Last login: Wed May 13 19:54:09 CDT 2020 on pts/1
-bash-4.2$ ls -lrt
total 56
-rw-r--r--. 1 decisionengine root   370 May 13 19:50 gce_test.py
-rwxr-xr-x. 1 decisionengine root 23764 May 13 19:52 GCEBillingInfo.py3
-rwxr-xr-x. 1 decisionengine root 24705 May 13 19:52 GCEBillingInfo.py
-bash-4.2$ whoami
decisionengine
-bash-4.2$ python3 gce_test.py 
-bash-4.2$ echo $?
0
---
where gce_test.py contains the code above.

So I am pretty sure the credential is right this time.

What's next, adding some more print statements to see what's happening?  you have access to fermicloud117.

**Comment by DmitryLitvintsev** [comment]
https://fermicloud140.fnal.gov/reviews/r/126/

**Comment by StevenCTimm** [comment]
The latest CI-generated rpm has this fix and the Biling info channel runs correctly.  Will hold this open until the 1.2 release is cut.

**Comment by StevenCTimm** [comment]
This issue is working in the 1.2.0 release and should be considered resolved.
