### ISSUE TITLE
py2.7 1.1.x version of Nersc_Allocation_Info still errors out and takes the channel offline

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#231]
The version of NerscAllocationInfo.py as released in 1.1.x still errors out and does not catch the exception correctly, knocking the channel offline.

    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR
    raise HTTPError(http_error_msg, response=self)
HTTPError: 502 Server Error: BAD GATEWAY
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: SERVICE UNAVAILABLE
    raise HTTPError(http_error_msg, response=self)
HTTPError: 502 Server Error: BAD GATEWAY
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR

**Comment by StevenCTimm** [comment]
2020-05-22 01:58:59,157 - root - TaskManager - 159023 - NerscAllocationInfo - ERROR - Exception running source NerscAllocationInfo
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 279, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 83, in acquire
    self.send_query()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 40, in send_query
    values = self.newt.get_usage(username)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.py", line 90, in get_usage
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR

---
it does not appear that any retries are attempted.

**Comment by DmitryLitvintsev** [comment]
Retries are implemented on the master only as far as I can tell. Wee can consider merging it from master

**Comment by shreyb** [comment]
Fixed in #233.  Here's the traceback from testing that we'd expect due to a retry error (as opposed to the one @StevenCTimm reported):

> 2020-05-28 09:49:58,760 - root - TaskManager - 3265 - NerscAllocationInfo - ERROR - Exception running source NerscAllocationInfo : HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt/login/ (Caused by ResponseError('too many 500 error responses',))
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 287, in run_source
>     data = src.worker.acquire()
>   File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 91, in acquire
>     self.send_query()
>   File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 48, in send_query
>     values = self.newt.get_usage(username)
>   File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.py", line 84, in get_usage
>     self._login()
>   File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.py", line 69, in _login
>     r = self.session.post(login_url, data=postfields)
>   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 578, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 507, in send
>     raise RetryError(e, request=request)
> RetryError: HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt/login/ (Caused by ResponseError('too many 500 error responses',))

**Comment by StevenCTimm** [comment]
I have installed the latest 1.1.2 rpm  (CI artifact dated 5/28/20) on a test machine and now we wait until NERSC goes offline again to see if it retries or not.

**Comment by StevenCTimm** [comment]
I have verified that the retry code is in this version of NerscAllocationInfo.  I have used a test vm to put the max_retries parameter into the config file and restarted the decision engine.

**Comment by StevenCTimm** [comment]
This version of the code as deployed on fermicloud155 has (thus far) kept the channel alive when all 3 production decision engines saw an outage on Nersc of significant length. ( more than an hour).. it looks promising.

**Comment by StevenCTimm** [comment]
Since Nersc stayed offline all overnight, the source eventually gave up
and exited after the 10 max retries, as configured.

2020-06-08 00:38:06,742 - urllib3.connectionpool - connectionpool - 12433 - NerscAllocationInfo - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=10)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ec027c610>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /newt//account/iris
2020-06-08 00:40:14,079 - root - TaskManager - 12433 - NerscAllocationInfo - ERROR - Exception running source NerscAllocationInfo : HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt//account/iris (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ec007a050>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 287, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 91, in acquire
    self.send_query()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 48, in send_query
    values = self.newt.get_usage(username)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/NERSC/util/newt.py", line 109, in get_usage
    data={"query": query})
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 529, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt//account/iris (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ec007a050>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2020-06-08 00:40:14,814 - root - TaskManager - 12433 - MainT

Pretty good evidence that the code is doing as it is told.

**Comment by StevenCTimm** [comment]
This issue is now in the release and should be considered resolved.
