### ISSUE TITLE
Branch 1.1.3 glide_frontend_element.py bool object is not callable

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#238]
This issue was occurring in the pre-release rpm as well but I did not notice it until I installed the 1.1.3 decisionengine-standard-library release.  It is only reproducible if there are actually jobs in the queue and the DE is attempting to request resources.

from resource_request.log

2020-06-08 21:06:51,035 - root - glidein_requests - 18508 - GlideinRequestManifests - INFO - --------------------------------------------
2020-06-08 21:06:51,035 - root - glidein_requests - 18508 - GlideinRequestManifests - INFO - Processing glidein requests for the FE Group: cms_all
2020-06-08 21:06:51,035 - root - glidein_requests - 18508 - GlideinRequestManifests - INFO - Frontend Group cms_all job query: VO=='cms' and CMS_JobType=='Production' and 
RequestCpus==1 and (RequestMemory/RequestCpus<=1308.0) and MaxWallTimeMins<=960 and RequestMaxInputRate<400
2020-06-08 21:06:51,036 - root - glidein_requests - 18508 - GlideinRequestManifests - INFO - Frontend Group cms_all site matching expression : GlideinName=='gfactory_insta
nce_cmssrv280' and GLIDEIN_Supported_VOs.str.contains('CMS') and GLIDEIN_CPUS >= 1 and GLIDEIN_Max_Walltime>=57600
2020-06-08 21:06:51,036 - root - glidein_requests - 18508 - GlideinRequestManifests - INFO - --------------------------------------------
2020-06-08 21:06:51,060 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Number of credentials found from the configuration 7
2020-06-08 21:06:51,169 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Jobs found total 10 idle 10 (good 10, old(10min 0, 60min 0), grid 10, vo
ms 10) running 0
2020-06-08 21:06:51,169 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Group slots found total 0 (limit 40000 curb 39000) idle 0 (limit 40000 c
urb 39000) running 0
2020-06-08 21:06:51,170 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Frontend slots found total 0 (limit 170000 curb 167000) idle 0 (limit 35
000 curb 25000) running 0
2020-06-08 21:06:51,170 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Overall slots found total 7 (limit 170000 curb 167000) idle 7 (limit 350
00 curb 25000) running 0
2020-06-08 21:06:52,861 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Number of credentials found: 7
2020-06-08 21:06:52,941 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Number of credentials found: 7
2020-06-08 21:06:53,010 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Number of credentials found: 7
2020-06-08 21:06:53,078 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO -             Jobs in schedd queues                 |           Slots     
    |       Cores       | Glidein Req | Factory Entry Information
2020-06-08 21:06:53,078 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Idle (match  eff   old  uniq )  Run ( here  max ) | Total  Idle   Run  F
ail | Total  Idle   Run | Idle MaxRun | State FigureOfMerit EntryName
2020-06-08 21:06:53,091 - root - glide_frontend_element - 18508 - GlideinRequestManifests - INFO - Request FNAL_HEPCLOUD_AWS_us-west-2a_r4_4xlarge@gfactory_instance_cmssrv
280@gfactory_service_cmssrv280: prop jobs 2(mc 1.0, min 0), available slots 0 
2020-06-08 21:06:53,156 - root - glidein_requests - 18508 - GlideinRequestManifests - ERROR - Error generating glidein requests: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/transforms/glidein_requests.py", line 153, in transform
    job_filter=job_query, fom_entries=fom_entries)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1308, in generate_glidein_requests
    factory_globals, job_filter=job_filter)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1576, in generate_glidein_requests_one
    limits_triggered)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1135, in compute_glidein_min_idle
    (global_total_idle_glideins >= self.global_total_max_slots_idle)):
TypeError: 'bool' object is not callable

2020-06-08 21:06:53,156 - root - TaskManager - 18508 - GlideinRequestManifests - ERROR - exception from transform GlideinRequestManifests : 'bool' object is not callable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 397, in run_transform
    data = transform.worker.transform(data_block)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/transforms/glidein_requests.py", line 153, in transform
    job_filter=job_query, fom_entries=fom_entries)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1308, in generate_glidein_requests
    factory_globals, job_filter=job_filter)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1576, in generate_glidein_requests_one
    limits_triggered)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1135, in compute_glidein_min_idle
    (global_total_idle_glideins >= self.global_total_max_slots_idle)):
TypeError: 'bool' object is not callable

----

There is a significant diff in this version which is put out in 1.1.3 and the 1.1.2 that we are currently running in production.

Please investigate.. I can make fermicloud155 available to you if necessary.

**Comment by StevenCTimm** [comment]
This  bug will also affect 1.2.0 branch as the code there is the same, even though we have not actually been able to get as far as to test it there.

I have installed the patched routine on fermicloud155 on top of the 1.1.3 branch and all channels in the 1.1.3 branch are running STEADY. .. this does not mean that the 1.1.3 branch is signed off yet but we are getting closer.

**Comment by StevenCTimm** [comment]
Hold this issue open until the patch makes it into the 1.1.x and 1.2.x branches.

**Comment by DmitryLitvintsev** [comment]
Fixed merged to 1.2 and 1.1 branches

**Comment by StevenCTimm** [comment]
This is now fixed in 1.1.4 branch as released.. test of 1.2.1 branch pending.

**Comment by StevenCTimm** [comment]
The patched code is in 1.2.1 branch as well.  Although we cannot yet test this routine glide_frontend_element.py without the python3 glideinwms libs, there is no reason to believe that it won't work.  We can close this issue and reopen if further problems come up.
