### ISSUE TITLE
Modify NERSCAllocation main() so that it can be run standalone

### ISSUE THREAD

**Issue by shreyb** [HEPCloud/decisionengine_modules#246]
This request comes from a discussion with @StevenCTimm - we want to be able to run NerscAllocationInfo as a standalone module (outside of the decision engine framework), so that when there are NERSC issues, we can send them code they can reproduce.  

This should be fairly straightforward - just adding a flag that runs the acquire() method of the NerscAllocationInfo class and dumps the output.

**Comment by shreyb** [comment]
Work notes:  This is finished.  Just need to test.

**Comment by shreyb** [comment]
Looks good, and passes unit tests:  @StevenCTimm does this work for your purposes?

### Good example
```
$ python3 NerscAllocationInfo.py --acquire-with-config /etc/decisionengine/config.d/Nersc.conf
{'Nersc_Allocation_Info':    projectId repoName repoType  currentAlloc  usedAlloc    uid  name firstname lastname middlename  userAlloc  userAllocPct
0      54807    m2612     REPO  3.744000e+11      560.0  72048  timm    Steven     Timm          C        0.0           2.0}
```

### Failing example
```
$ python3 NerscAllocationInfo.py --acquire-with-config /etc/decisionengine/config.d/Nersc.conf.BAD
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 820, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt/login/ (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NerscAllocationInfo.py", line 165, in <module>
    main()
  File "NerscAllocationInfo.py", line 159, in main
    print(n.acquire())
  File "NerscAllocationInfo.py", line 91, in acquire
    self.send_query()
  File "NerscAllocationInfo.py", line 48, in send_query
    values = self.newt.get_usage(username)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/util/newt.py", line 84, in get_usage
    self._login()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/util/newt.py", line 69, in _login
    r = self.session.post(login_url, data=postfields)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='newt.nersc.gov', port=443): Max retries exceeded with url: /newt/login/ (Caused by ResponseError('too many 500 error responses',))
```

**Comment by shreyb** [comment]
And here's the help text for NerscAllocationInfo:
```
$ python3 NerscAllocationInfo.py --help
usage: NerscAllocationInfo.py [-h] [--configtemplate] [--configinfo]
                              [--acquire-with-config CONFIG_FILE]

optional arguments:
  -h, --help            show this help message and exit
  --configtemplate      prints the expected module configuration
  --configinfo          prints config template along with produces and
                        consumes info
  --acquire-with-config CONFIG_FILE
                        Tries to contact NERSC with the provided config file
                        and pulls data according to config
```

**Comment by StevenCTimm** [comment]
Which branch is this version of NerscAllocationInfo.py, in, please advise.

**Comment by shreyb** [comment]
Sorry I didn't make this clear - it's branch 246 in my fork:

https://github.com/shreyb/decisionengine_modules/tree/246

**Comment by StevenCTimm** [comment]
I verify that it works with NERSC up, will try again with NERSC down tomorrow.

**Comment by shreyb** [comment]
Hi Steve - any updates on this?

**Comment by StevenCTimm** [comment]
NERSC never actually took their web services down during this 4 day downtime so we never actually got a look at how the failure mode works, but I have no doubt that this has been done correctly and it should be ok to merge things in.

**Comment by shreyb** [comment]
@DmitryLitvintsev - can this be merged?

**Comment by shreyb** [comment]
My mistake - I thought this was an open PR.  I will start the review process for this.

**Comment by shreyb** [comment]
Opened review request 182.

**Comment by knoepfel** [comment]
@shreyb, looks good.  Can you create the PR from your branch?

**Comment by StevenCTimm** [comment]
Shreyas, did this finally get merged?  If so did it make the 1.3.0 release?

**Comment by shreyb** [comment]
Since #256 was merged, can we go ahead and close this out?

**Comment by StevenCTimm** [comment]
yes this is working in the 1.3 release we can close this one out.

**Comment by shreyb** [comment]
Great - closing it.
