### ISSUE TITLE
New exception in NERSC newt get_usage

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#281]
There are many exceptions against the NERSC newt API which have been fixed by recent retries but we have 
recently observed a new one for which a retry is apparently not being made.

2020-10-23 00:02:04,758 - root - TaskManager - 221253 - NerscAllocationInfo - ERROR - Exception running source NerscAllocationInfo : 502 Server Error: BAD GATEWAY for url: https://newt.nersc.gov/newt//account/iris
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 301, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 92, in acquire
    self.send_query()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 49, in send_query
    values = self.newt.get_usage(username)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/util/newt.py", line 110, in get_usage
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: BAD GATEWAY for url: https://newt.nersc.gov/newt//account/iris

**Comment by StevenCTimm** [comment]
We also observe this exception from time to time:

2020-10-26 21:32:05,700 - root - TaskManager - 28892 - NerscAllocationInfo - ERROR - Exception running source NerscAllocationInfo : 504 Server Error: GATEWAY TIMEOUT for url: https://newt.nersc.gov/newt//account/iris
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 301, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 92, in acquire
    self.send_query()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/sources/NerscAllocationInfo.py", line 49, in send_query
    values = self.newt.get_usage(username)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/NERSC/util/newt.py", line 110, in get_usage
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: GATEWAY TIMEOUT for url: https://newt.nersc.gov/newt//account/iris

**Comment by shreyb** [comment]
Add 502, 504, and any other 500 codes here:
https://github.com/HEPCloud/decisionengine_modules/blob/master/NERSC/util/newt.py#L51

This can just be hardcoded, but hopefully there's a nice requests way to do it.  If not by the end of the morning, just add a bunch to the list.  There's a larger discussion regarding error handling anyway, and that will probably wipe this change out.

**Comment by shreyb** [comment]
This works: 
`[code for code in requests.status_codes._codes if code >=500]`

but upon further discussion with Dmitry, we only want to retry 500, 502, 503, 504, 507.  So I'll just hardcode those for now.

**Comment by shreyb** [comment]
Opened review board request: https://fermicloud140.fnal.gov/reviews/r/261/
