### ISSUE TITLE
Unit test tests/test_job_q.py is failing

### ISSUE THREAD

**Issue by vitodb** [HEPCloud/decisionengine_modules#293]
Since Dec 1st the unit test tests/test_job_q.py is failing, though there has been any code change since days before.
This unit test is failing for both master and 1.4 branches.
The unit test log can be accessed from [Jenkins](https://buildmaster.fnal.gov/buildmaster/view/CI/job/decisionengine_modules_pipeline/407/execution/node/116/log/)
For convenience the excerpt of the test error message is below:
```
=================================== FAILURES ===================================
____________________________ TestJobQ.test_condorq _____________________________
Traceback (most recent call last):
  File "/scratch/workspace/decisionengine_modules_pipeline/unit_tests@2/decisionengine_modules/tests/test_job_q.py", line 31, in test_condorq
    f.return_value = utils.input_from_file(FIXTURE_FILE)
  File "/scratch/workspace/decisionengine_modules_pipeline/unit_tests@2/decisionengine_modules/util/testutils.py", line 9, in input_from_file
    return eval(fd.read())
  File "<string>", line 76, in <module>
AttributeError: module 'classad' has no attribute 'Value'
=========================== short test summary info ============================
FAILED decisionengine_modules/tests/test_job_q.py::TestJobQ::test_condorq - A...
=================== 1 failed, 91 passed, 1 warning in 38.56s ===================
```

**Comment by DmitryLitvintsev** [comment]
PR https://github.com/HEPCloud/decisionengine_modules/pull/294 fixed this issue
