### ISSUE TITLE
Two modules (Gce and AWS_Calculation_with_source_proxy) exit with exceptions

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#326]
Version 1.6.1 framework / version 1.6.0 modules 
We observed two channels go offline due to the graphite endpoint (hepcmetrics.fnal.gov ) being temporarily
not available.  This is significant because we have never ever seen any error in a Publisher take a channel offline,
and this one did.

Investigation showed that the site hepcmetrics.fnal.gov had been rebooted at this time.

**Comment by StevenCTimm** [comment]
So this could actually be a modules issue or a framework issue--due to the rework of the logic engine it could be that 
exceptions are handled differently now in publishers.. we will have to investigate.

**Comment by StevenCTimm** [comment]
This has now been shown to be reproducible--if graphite goes down, the publishers
fail and the 2 channels go offline.  This is the exception:


2021-06-24T14:13:30-0500 - root - TaskManager - 26421 - MainThread - ERROR - Unexpected error!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 47, in send_dict
    s.connect((self.graphite_host, self.graphite_pickle_port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 510, in run_publishers
    publisher.worker.publish(data_block)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite/publishers/generic_publisher.py", line 57, in publish
    debug_print=False, send_data=True)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 50, in send_dict
    logging.getLogger.exception(f"Error sending data to graphite at {self.graphite_host}:{self.graphite_pickle_port}: {detail}")
AttributeError: 'function' object has no attribute 'exception'
2021-06-24T14:13:30-0500 - root - TaskManager - 26421 - MainThread - ERROR - error in decision cycle(publishers) 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 47, in send_dict
    s.connect((self.graphite_host, self.graphite_pickle_port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 302, in decision_cycle
    a_f['actions'], a_f['newfacts'], data_block_t1)
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 510, in run_publishers
    publisher.worker.publish(data_block)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite/publishers/generic_publisher.py", line 57, in publish
    debug_print=False, send_data=True)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 50, in send_dict
    logging.getLogger.exception(f"Error sending data to graphite at {self.graphite_host}:{self.graphite_pickle_port}: {detail}")
AttributeError: 'function' object has no attribute 'exception'

Although this is in the "modules" section I believe it is in fact a framework issue.,

The 1.5 framework still being run on cmsde01 / gpde01 doesn't do this even though it is trying
to publish to the same down graphite server.

Publisher exceptions didn't use to take channels down, now they do.

**Comment by knoepfel** [comment]
Steve, thanks for pointing this out.  We should talk about what the expected framework behavior should be, but this issue can be addressed locally in the meantime.

**Comment by StevenCTimm** [comment]
More general issue has been filed in #369

**Comment by StevenCTimm** [comment]
This is now fixed and in production with 1.7.1
