### ISSUE TITLE
Add retries to all publishers that contact Graphite

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#369]
We are seeing on a more-than-weekly basis that publishers time out and take a whole channel offline.
This is related to framework issue 
https://github.com/HEPCloud/decisionengine/issues/411

But it appears that there may not be an easy fix on the framework side so I am requesting that 
the modules be fixed, particularly those which talk to Graphite, which has been going down more than usual recently,
so that if the send to Graphite fails, it waits a minute or two and then tries again.  Either that or just catch the
exception in such a way that the whole channel doesn't go offline.

Steve Timm

**Comment by knoepfel** [comment]
@StevenCTimm, can you post the relevant stack trace where the exception is occurring?  I see some exception-handling in the `Graphite.send_dict` method, but I need to know specifically what errors you're encountering.

**Comment by StevenCTimm** [comment]
2021-09-09T16:41:14-0500 - root - TaskManager - 4369 - MainThread - ERROR - Unexpected error!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 47, in send_dict
    s.connect((self.graphite_host, self.graphite_pickle_port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 510, in run_publishers
    publisher.worker.publish(data_block)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/publishers/AWS_generic_publisher.py", line 52, in publish
    data)[1], debug_print=False, send_data=True)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 50, in send_dict
    logging.getLogger.exception(f"Error sending data to graphite at {self.graphite_host}:{self.graphite_pickle_port}: {detail}")
AttributeError: 'function' object has no attribute 'exception'
2021-09-09T16:41:14-0500 - root - TaskManager - 4369 - MainThread - ERROR - error in decision cycle(publishers) 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 47, in send_dict
    s.connect((self.graphite_host, self.graphite_pickle_port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 302, in decision_cycle
    a_f['actions'], a_f['newfacts'], data_block_t1)
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 510, in run_publishers
    publisher.worker.publish(data_block)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/publishers/AWS_generic_publisher.py", line 52, in publish
    data)[1], debug_print=False, send_data=True)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/graphite_client.py", line 50, in send_dict
    logging.getLogger.exception(f"Error sending data to graphite at {self.graphite_host}:{self.graphite_pickle_port}: {detail}")
AttributeError: 'function' object has no attribute 'exception'

**Comment by knoepfel** [comment]
Thanks @StevenCTimm.  The `AttributeError: 'function' object has no attribute 'exception'` error is fixed with decisionengine_modules 1.7.0.  However, the `socket.gaierror` error is the root cause.  I will adjust the configurability of `graphite_client` and use the `retry_function` facility already available through decisionengine_modules.

**Comment by StevenCTimm** [comment]
This is a super issue of module issue #326 --the root cause of this one and 326 are the same.

**Comment by StevenCTimm** [comment]
Kyle has a patch for this which has been merged to trunk and works.  Just have to keep watching this until it makes it into a release.

**Comment by StevenCTimm** [comment]
Also request that when time permits this fix be back-ported into the 1.7 branch.

**Comment by StevenCTimm** [comment]
This was successfully released in 1.7.1.  Closing.
