### ISSUE TITLE
Exception "list index out of range"

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#52]
From /var/log/decision/decision_engine_log

```
2019-04-25 11:01:31,080 - decision_engine - glidein_requests - GlideinRequestManifests - INFO - Processing glidein requests for the FE Group: fife_all
2019-04-25 11:01:31,081 - decision_engine - glidein_requests - GlideinRequestManifests - INFO - Frontend Group fife_all job query: (VO=='fermilab' or x509UserProxyVOName=='fermilab') and x509UserProxyFirstFQAN.str.contains('/fermilab/Role=Production') and RequestCpus==1 and (RequestMemory/RequestCpus<=1308.0) and JOB_EXPECTED_MAX_LIFETIME<=57600 and RequestMaxInputRate<400
2019-04-25 11:01:31,081 - decision_engine - glidein_requests - GlideinRequestManifests - INFO - Frontend Group fife_all site matching expression : (GLIDEIN_Supported_VOs.str.contains('FERMILAB') or GLIDEIN_Supported_VOs.str.contains('Fermilab')) and GLIDEIN_CPUS >= 1 and GLIDEIN_Max_Walltime>=57600
2019-04-25 11:01:31,081 - decision_engine - glidein_requests - GlideinRequestManifests - INFO - --------------------------------------------
2019-04-25 11:01:31,092 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Number of credentials found from the configuration 6
2019-04-25 11:01:31,169 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Jobs found total 113 idle 24 (good 24, old(10min 24, 60min 0), grid 24, voms 24) running 89
2019-04-25 11:01:31,169 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Group slots found total 19810 (limit 20000 curb 19000) idle 306 (limit 20000 curb 19000) running 19030
2019-04-25 11:01:31,169 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Frontend slots found total 19810?? (limit 170000 curb 167000) idle?? 306 (limit 35000 curb 25000) running 19030??
2019-04-25 11:01:31,169 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Overall slots found total 19810?? (limit 170000 curb 167000) idle?? 306 (limit 35000 curb 25000) running 19030??
2019-04-25 11:01:31,912 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Number of credentials found: 6
2019-04-25 11:01:31,950 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO -             Jobs in schedd queues                 |           Slots         |       Cores       | Glidein Req | Factory Entry Information
2019-04-25 11:01:31,950 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO - Idle (match  eff   old  uniq )  Run ( here  max ) | Total  Idle   Run  Fail | Total  Idle   Run | Idle MaxRun | State FigureOfMerit EntryName
2019-04-25 11:01:31,964 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO -     0(    0     0     0     0)     0(    0 20000) |     0     0     0     0 |     0     0     0 |     0     0 | Down         0.4621 FNAL_HEPCLOUD_GOOGLE_us-central1-a_custom-32-65536@gfactory_instance_fermifactory02@gfactory_service_fermifactory02@fermifactory02.fnal.gov
2019-04-25 11:01:31,976 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO -     9(   24     9     9     0)    89(    0 20000) |     0     0     0     0 |     0     0     0 |     0     0 | Up           0.0060 FIFE_T3_US_NERSC_Cori@gfactory_instance_fermifactory02@gfactory_service_fermifactory02@fermifactory02.fnal.gov
2019-04-25 11:01:31,987 - decision_engine - glide_frontend_element - GlideinRequestManifests - INFO -     0(    0     0     0     0)     0(    0 20000) |     0     0     0     0 |     0     0     0 |     0     0 | Down         0.0219 FIFE_T3_US_NERSC_Edison@gfactory_instance_fermifactory02@gfactory_service_fermifactory02@fermifactory02.fnal.gov
2019-04-25 11:01:31,998 - decision_engine - glidein_requests - GlideinRequestManifests - ERROR - Error generating glidein requests: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/transforms/glidein_requests.py", line 155, in transform
    job_filter=job_query, fom_entries=fom_entries)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1226, in generate_glidein_requests
    factory_globals, job_filter=job_filter)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/glide_frontend_element.py", line 1467, in generate_glidein_requests_one
    fom = fom_info.get('FOM').tolist()[0]
IndexError: list index out of range

2019-04-25 11:01:31,999 - decision_engine - TaskManager - GlideinRequestManifests - ERROR - exception from transform GlideinRequestManifests list index out of range
```

Notes on the above:

1) the up/down state of the entries is somehow cached because the current output shows FIFE_T3_US_NERSC_Edison as down and it is in fact up.

2) The decision engine can run indefinitely as long as there are no jobs, but as soon as we do put in some jobs this error will happen

3) at first this error happened when there was only one entry live in the whole factory.
Now there are five entries are live and the same thing is happening.

4) the list of entries is being truncated above--there are more entries than that which match the 
entries selection expression.. presumably we are hitting some exception as we are trying to process one of them.

**Comment by DmitryLitvintsev** [comment]
fixed  [[https://github.com/HEPCloud/decisionengine_modules/commit/e7e3bbc1afdd75cfba7170c05dfbba4c96d0bc7d][e7e3bbc1afdd75cfba7170c05dfbba4c96d0bc7d]]
