### ISSUE TITLE
DE has problem advertisiing to new OSG factory gfactory-2.opensciencegrid.org

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#55]
The decision engine is hitting an exception advertising to the new gfactory-2.opensciencegrid.org

factory.  (old factory gfactory-1.t2.ucsd.edu is ok)

2019-05-24 13:22:15,838 - decision_engine - publisher - MainThread - ERROR - ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/site-packages/decisionengine_modules/htcondor/publishers/publisher.py", line 149, in publish_to_htcondor\n    self.condor_advertise(ads, collector_host=collector)\n', '  File "/usr/lib/python2.7/site-packages/decisionengine_modules/htcondor/publishers/publisher.py", line 101, in condor_advertise\n    collector.advertise(ads, update_ad_command, True)\n', 'ValueError: Failed to advertise to collector\n']

the CollectorLog on far end says

CollectorLog.old:05/23/19 14:24:54 (pid:3543588) DC_AUTHENTICATE: required authentication of 131.225.240.95 failed: AUTHENTICATE:1003:Failed to authenticate with any method|AUTHENTICATE:1004:Failed to authenticate using GSI|GSI:5005:Failed to authenticate with client.  Client does not trust our certificate.  You may want to check the GSI_DAEMON_NAME in the condor_config|AUTHENTICATE:1004:Failed to authenticate using FS|FS:1004:Unable to lstat(/tmp/FS_XXXdy4H8p)

Of course it could be a problem on their end.. my question is, is there any way to dump a glideclientglobal

classad to /tmp somewhere so we can try to do the condor_advertise by hand with TOOL_DEBUG set

to D_ALL So we can see what is going on on our end?

(will also open an Issue about this)

Thanks

Steve Timm

**Comment by DmitryLitvintsev** [comment]
We can close this issue.. there is still a configuration issue that will have to be resolved to make sure the right option is in the condor_config file but this is not a decision engine coding issue at this time.
